-- TRUNCATE TABLE ADMINBASKET
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMINBASKET."users" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ADMINBASKET."userDetails" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ADMINBASKET."product" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ADMINBASKET."productList" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ADMINBASKET."wishList" CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

create table "users" (
    "user_id" INTEGER GENERATED BY DEFAULT as identity primary key,
    "user_name" VARCHAR(30) not null unique,
    "password" VARCHAR2(500),
    "profile_img_url" VARCHAR(255),
    "user_nickname" VARCHAR(36) NOT NULL unique,
    "role" varchar(10) default 'BUYER'
    );
create table "userDetails"(
    "detail_user_no" Integer primary key,
    CONSTRAINT "user_id"
        foreign key ("detail_user_no")
            references "users"("user_id")
                on delete cascade,
    "email" VARCHAR(100) NOT NULL UNIQUE,
    "phone" VARCHAR(15) NOT NULL UNIQUE,
    "privacy_agreements" Number(1) DEFAULT '0' NOT NULL,
    "marketing_agreements" Number(1) DEFAULT '0' NOT NULL,
    "created_at" TIMESTAMP default sysdate NOT NULL ,
    "birth_date" DATE NOT NULL,
    "name" VARCHAR(30) NOT NULL
);
create table "product"(
    "product_id" INTEGER GENERATED BY DEFAULT as identity primary key,
    "product_category" VARCHAR(15) not null,
    "product_name" VARCHAR(100) not null,
    "product_img_url" VARCHAR(255),
    "product_description" varchar2(3000),
    "product_price" INTEGER NOT NULL,
    "product_user_no" Integer,
    CONSTRAINT "product_user_no"
        foreign key ("product_user_no")
            references "users"("user_id")  /* 올린 사람의 ID를 알기 위해서 */
        on delete cascade,                 /* 판매자 이름을 알기 위해서라면 */
    "product_quantity" NUMBER(6) NOT NULL
);

create table "productList"(
    "cart_item_id" INTEGER GENERATED BY DEFAULT as identity primary key,
    "product_no" INTEGER,
    CONSTRAINT "product_id"
    foreign key("product_no")
    references "product"("product_id") on delete cascade,
    "list_user_no" Integer,
    CONSTRAINT "list_user_no"
        foreign key ("list_user_no")
            references "users"("user_id"),
    "quantity" Integer DEFAULT 1,
    "added_at" DATE DEFAULT SYSDATE not null
);

create table "wishList" (
    "wish_user_no" INTEGER,
    CONSTRAINT "wish_user_no"
    foreign key ("wish_user_no")
    references "users"("user_id"),
    "wish_product_no" INTEGER,
    CONSTRAINT "wish_product_no"
    foreign key ("wish_product_no")
    references "product"("product_id"),
    primary key ("wish_user_no","wish_product_no"),
    "added_at" DATE DEFAULT SYSDATE not null
)
