BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMINBASKET.users CASCADE CONSTRAINTS PURGE ';
    EXECUTE IMMEDIATE 'DROP TABLE ADMINBASKET.userDetails CASCADE CONSTRAINTS PURGE ';
    EXECUTE IMMEDIATE 'DROP TABLE ADMINBASKET.product CASCADE CONSTRAINTS PURGE ';
    EXECUTE IMMEDIATE 'DROP TABLE ADMINBASKET.cartItemList CASCADE CONSTRAINTS PURGE ';
    EXECUTE IMMEDIATE 'DROP TABLE ADMINBASKET.wishList CASCADE CONSTRAINTS PURGE ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
PURGE RECYCLEBIN;
create table users (
    user_id Integer GENERATED BY DEFAULT as identity primary key,
    user_name VARCHAR(30) not null unique,
    password VARCHAR2(500),
    profile_img_url VARCHAR(255),
    user_nickname VARCHAR(36) NOT NULL unique,
    role varchar(10) default 'BUYER'
    );
create table userDetails(
    detail_user_no Integer primary key,
    CONSTRAINT detail_user_no
        foreign key (detail_user_no)
            references users(user_id)
                on delete cascade,
    email VARCHAR(100) UNIQUE,
    phone VARCHAR(15) NOT NULL UNIQUE,
    privacy_agreements Number(1) DEFAULT '0' NOT NULL,
    marketing_agreements Number(1) DEFAULT '0' NOT NULL,
    created_at TIMESTAMP default SYSTIMESTAMP NOT NULL ,
    birth_date TIMESTAMP NOT NULL,
    name VARCHAR(30) NOT NULL
);
CREATE TABLE product (
     product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     product_category VARCHAR(15) NOT NULL,
     product_name VARCHAR(100) NOT NULL UNIQUE,
     product_img_url VARCHAR(255),
     product_description VARCHAR2(3000),
     product_price INTEGER NOT NULL,
     product_user_no INTEGER,
     CONSTRAINT product_user_no
         FOREIGN KEY (product_user_no)
             REFERENCES users(user_id)
                 ON DELETE CASCADE,
     product_quantity INTEGER NOT NULL,
     product_added_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE cartItemList (
      cart_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_no INTEGER,
      CONSTRAINT product_no
          FOREIGN KEY (product_no)
              REFERENCES product(product_id)
                  ON DELETE CASCADE,
      list_user_no INTEGER,
      CONSTRAINT list_user_no
          FOREIGN KEY (list_user_no)
              REFERENCES users(user_id),
      quantity INTEGER DEFAULT 1,
      added_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE wishList (
      wish_user_no INTEGER,
      CONSTRAINT wish_user_no
          FOREIGN KEY (wish_user_no)
              REFERENCES users(user_id),
      wish_product_no INTEGER,
      CONSTRAINT wish_product_no
          FOREIGN KEY (wish_product_no)
              REFERENCES product(product_id),
      PRIMARY KEY (wish_user_no, wish_product_no),
      added_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    );
